// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type HealthCheck struct {
	ID        int64
	Name      string
	Url       string
	Interval  int64
	CreatedAt sql.NullTime
}

type HealthCheckResult struct {
	ID            int64
	HealthCheckID int64
	Status        string
	Message       sql.NullString
	CheckedAt     sql.NullTime
}

type LogEntry struct {
	ID          int64
	ContainerID string
	Timestamp   time.Time
	Message     string
	UniqueID    string
	LogLevel    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProxySite struct {
	ID            int64
	ContainerName string
	Port          string
	Domain        string
	CreatedAt     sql.NullTime
}

type User struct {
	ID             int64
	Username       string
	HashedPassword string
	TotpSecret     sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
